//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SampleClient.SampleServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SampleServiceReference.ServiceSample")]
    public interface ServiceSample {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ServiceSample/GetData", ReplyAction="http://tempuri.org/ServiceSample/GetDataResponse")]
        string GetData();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ServiceSample/GetData", ReplyAction="http://tempuri.org/ServiceSample/GetDataResponse")]
        System.Threading.Tasks.Task<string> GetDataAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ServiceSample/GetMessage", ReplyAction="http://tempuri.org/ServiceSample/GetMessageResponse")]
        string GetMessage(string Name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ServiceSample/GetMessage", ReplyAction="http://tempuri.org/ServiceSample/GetMessageResponse")]
        System.Threading.Tasks.Task<string> GetMessageAsync(string Name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ServiceSample/GetResult", ReplyAction="http://tempuri.org/ServiceSample/GetResultResponse")]
        string GetResult(SampleServiceLib.Student s);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ServiceSample/GetResult", ReplyAction="http://tempuri.org/ServiceSample/GetResultResponse")]
        System.Threading.Tasks.Task<string> GetResultAsync(SampleServiceLib.Student s);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ServiceSample/GetMax", ReplyAction="http://tempuri.org/ServiceSample/GetMaxResponse")]
        int GetMax(System.Collections.Generic.List<int> ar);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ServiceSample/GetMax", ReplyAction="http://tempuri.org/ServiceSample/GetMaxResponse")]
        System.Threading.Tasks.Task<int> GetMaxAsync(System.Collections.Generic.List<int> ar);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ServiceSample/GetSorted", ReplyAction="http://tempuri.org/ServiceSample/GetSortedResponse")]
        System.Collections.Generic.List<int> GetSorted(System.Collections.Generic.List<int> ar);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ServiceSample/GetSorted", ReplyAction="http://tempuri.org/ServiceSample/GetSortedResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<int>> GetSortedAsync(System.Collections.Generic.List<int> ar);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ServiceSample/GetTopper", ReplyAction="http://tempuri.org/ServiceSample/GetTopperResponse")]
        SampleServiceLib.Student GetTopper(System.Collections.Generic.List<SampleServiceLib.Student> ls);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ServiceSample/GetTopper", ReplyAction="http://tempuri.org/ServiceSample/GetTopperResponse")]
        System.Threading.Tasks.Task<SampleServiceLib.Student> GetTopperAsync(System.Collections.Generic.List<SampleServiceLib.Student> ls);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ServiceSample/GetCountries", ReplyAction="http://tempuri.org/ServiceSample/GetCountriesResponse")]
        System.Collections.Generic.List<SampleServiceLib.Country> GetCountries();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ServiceSample/GetCountries", ReplyAction="http://tempuri.org/ServiceSample/GetCountriesResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<SampleServiceLib.Country>> GetCountriesAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ServiceSampleChannel : SampleClient.SampleServiceReference.ServiceSample, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceSampleClient : System.ServiceModel.ClientBase<SampleClient.SampleServiceReference.ServiceSample>, SampleClient.SampleServiceReference.ServiceSample {
        
        public ServiceSampleClient() {
        }
        
        public ServiceSampleClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceSampleClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceSampleClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceSampleClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GetData() {
            return base.Channel.GetData();
        }
        
        public System.Threading.Tasks.Task<string> GetDataAsync() {
            return base.Channel.GetDataAsync();
        }
        
        public string GetMessage(string Name) {
            return base.Channel.GetMessage(Name);
        }
        
        public System.Threading.Tasks.Task<string> GetMessageAsync(string Name) {
            return base.Channel.GetMessageAsync(Name);
        }
        
        public string GetResult(SampleServiceLib.Student s) {
            return base.Channel.GetResult(s);
        }
        
        public System.Threading.Tasks.Task<string> GetResultAsync(SampleServiceLib.Student s) {
            return base.Channel.GetResultAsync(s);
        }
        
        public int GetMax(System.Collections.Generic.List<int> ar) {
            return base.Channel.GetMax(ar);
        }
        
        public System.Threading.Tasks.Task<int> GetMaxAsync(System.Collections.Generic.List<int> ar) {
            return base.Channel.GetMaxAsync(ar);
        }
        
        public System.Collections.Generic.List<int> GetSorted(System.Collections.Generic.List<int> ar) {
            return base.Channel.GetSorted(ar);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<int>> GetSortedAsync(System.Collections.Generic.List<int> ar) {
            return base.Channel.GetSortedAsync(ar);
        }
        
        public SampleServiceLib.Student GetTopper(System.Collections.Generic.List<SampleServiceLib.Student> ls) {
            return base.Channel.GetTopper(ls);
        }
        
        public System.Threading.Tasks.Task<SampleServiceLib.Student> GetTopperAsync(System.Collections.Generic.List<SampleServiceLib.Student> ls) {
            return base.Channel.GetTopperAsync(ls);
        }
        
        public System.Collections.Generic.List<SampleServiceLib.Country> GetCountries() {
            return base.Channel.GetCountries();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<SampleServiceLib.Country>> GetCountriesAsync() {
            return base.Channel.GetCountriesAsync();
        }
    }
}
