//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SampleClient.SampleServiceReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Student", Namespace="http://schemas.datacontract.org/2004/07/TestService")]
    [System.SerializableAttribute()]
    public partial class Student : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int M1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int M2Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int M3Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int SidField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int M1 {
            get {
                return this.M1Field;
            }
            set {
                if ((this.M1Field.Equals(value) != true)) {
                    this.M1Field = value;
                    this.RaisePropertyChanged("M1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int M2 {
            get {
                return this.M2Field;
            }
            set {
                if ((this.M2Field.Equals(value) != true)) {
                    this.M2Field = value;
                    this.RaisePropertyChanged("M2");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int M3 {
            get {
                return this.M3Field;
            }
            set {
                if ((this.M3Field.Equals(value) != true)) {
                    this.M3Field = value;
                    this.RaisePropertyChanged("M3");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Sid {
            get {
                return this.SidField;
            }
            set {
                if ((this.SidField.Equals(value) != true)) {
                    this.SidField = value;
                    this.RaisePropertyChanged("Sid");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Country", Namespace="http://schemas.datacontract.org/2004/07/TestService")]
    [System.SerializableAttribute()]
    public partial class Country : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SampleServiceReference.ServiceSample")]
    public interface ServiceSample {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ServiceSample/GetData", ReplyAction="http://tempuri.org/ServiceSample/GetDataResponse")]
        string GetData();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ServiceSample/GetData", ReplyAction="http://tempuri.org/ServiceSample/GetDataResponse")]
        System.Threading.Tasks.Task<string> GetDataAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ServiceSample/GetMessage", ReplyAction="http://tempuri.org/ServiceSample/GetMessageResponse")]
        string GetMessage(string Name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ServiceSample/GetMessage", ReplyAction="http://tempuri.org/ServiceSample/GetMessageResponse")]
        System.Threading.Tasks.Task<string> GetMessageAsync(string Name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ServiceSample/GetResult", ReplyAction="http://tempuri.org/ServiceSample/GetResultResponse")]
        string GetResult(SampleClient.SampleServiceReference.Student s);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ServiceSample/GetResult", ReplyAction="http://tempuri.org/ServiceSample/GetResultResponse")]
        System.Threading.Tasks.Task<string> GetResultAsync(SampleClient.SampleServiceReference.Student s);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ServiceSample/GetMax", ReplyAction="http://tempuri.org/ServiceSample/GetMaxResponse")]
        int GetMax(System.Collections.Generic.List<int> ar);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ServiceSample/GetMax", ReplyAction="http://tempuri.org/ServiceSample/GetMaxResponse")]
        System.Threading.Tasks.Task<int> GetMaxAsync(System.Collections.Generic.List<int> ar);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ServiceSample/GetSorted", ReplyAction="http://tempuri.org/ServiceSample/GetSortedResponse")]
        System.Collections.Generic.List<int> GetSorted(System.Collections.Generic.List<int> ar);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ServiceSample/GetSorted", ReplyAction="http://tempuri.org/ServiceSample/GetSortedResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<int>> GetSortedAsync(System.Collections.Generic.List<int> ar);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ServiceSample/GetTopper", ReplyAction="http://tempuri.org/ServiceSample/GetTopperResponse")]
        SampleClient.SampleServiceReference.Student GetTopper(System.Collections.Generic.List<SampleClient.SampleServiceReference.Student> ls);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ServiceSample/GetTopper", ReplyAction="http://tempuri.org/ServiceSample/GetTopperResponse")]
        System.Threading.Tasks.Task<SampleClient.SampleServiceReference.Student> GetTopperAsync(System.Collections.Generic.List<SampleClient.SampleServiceReference.Student> ls);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ServiceSample/GetCountries", ReplyAction="http://tempuri.org/ServiceSample/GetCountriesResponse")]
        System.Collections.Generic.List<SampleClient.SampleServiceReference.Country> GetCountries();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ServiceSample/GetCountries", ReplyAction="http://tempuri.org/ServiceSample/GetCountriesResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<SampleClient.SampleServiceReference.Country>> GetCountriesAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ServiceSampleChannel : SampleClient.SampleServiceReference.ServiceSample, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceSampleClient : System.ServiceModel.ClientBase<SampleClient.SampleServiceReference.ServiceSample>, SampleClient.SampleServiceReference.ServiceSample {
        
        public ServiceSampleClient() {
        }
        
        public ServiceSampleClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceSampleClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceSampleClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceSampleClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GetData() {
            return base.Channel.GetData();
        }
        
        public System.Threading.Tasks.Task<string> GetDataAsync() {
            return base.Channel.GetDataAsync();
        }
        
        public string GetMessage(string Name) {
            return base.Channel.GetMessage(Name);
        }
        
        public System.Threading.Tasks.Task<string> GetMessageAsync(string Name) {
            return base.Channel.GetMessageAsync(Name);
        }
        
        public string GetResult(SampleClient.SampleServiceReference.Student s) {
            return base.Channel.GetResult(s);
        }
        
        public System.Threading.Tasks.Task<string> GetResultAsync(SampleClient.SampleServiceReference.Student s) {
            return base.Channel.GetResultAsync(s);
        }
        
        public int GetMax(System.Collections.Generic.List<int> ar) {
            return base.Channel.GetMax(ar);
        }
        
        public System.Threading.Tasks.Task<int> GetMaxAsync(System.Collections.Generic.List<int> ar) {
            return base.Channel.GetMaxAsync(ar);
        }
        
        public System.Collections.Generic.List<int> GetSorted(System.Collections.Generic.List<int> ar) {
            return base.Channel.GetSorted(ar);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<int>> GetSortedAsync(System.Collections.Generic.List<int> ar) {
            return base.Channel.GetSortedAsync(ar);
        }
        
        public SampleClient.SampleServiceReference.Student GetTopper(System.Collections.Generic.List<SampleClient.SampleServiceReference.Student> ls) {
            return base.Channel.GetTopper(ls);
        }
        
        public System.Threading.Tasks.Task<SampleClient.SampleServiceReference.Student> GetTopperAsync(System.Collections.Generic.List<SampleClient.SampleServiceReference.Student> ls) {
            return base.Channel.GetTopperAsync(ls);
        }
        
        public System.Collections.Generic.List<SampleClient.SampleServiceReference.Country> GetCountries() {
            return base.Channel.GetCountries();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<SampleClient.SampleServiceReference.Country>> GetCountriesAsync() {
            return base.Channel.GetCountriesAsync();
        }
    }
}
