USE [master]
GO
ALTER DATABASE [WebApiSecurityDb] SET COMPATIBILITY_LEVEL = 110
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC WebApiSecurityDb.[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE WebApiSecurityDb SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [WebApiSecurityDb] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [WebApiSecurityDb] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [WebApiSecurityDb] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [WebApiSecurityDb] SET ARITHABORT OFF 
GO
ALTER DATABASE [WebApiSecurityDb] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [WebApiSecurityDb] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [WebApiSecurityDb] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [WebApiSecurityDb] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [WebApiSecurityDb] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [WebApiSecurityDb] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [WebApiSecurityDb] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [WebApiSecurityDb] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [WebApiSecurityDb] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [WebApiSecurityDb] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [WebApiSecurityDb] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [WebApiSecurityDb] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [WebApiSecurityDb] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [WebApiSecurityDb] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [WebApiSecurityDb] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [WebApiSecurityDb] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [WebApiSecurityDb] SET  MULTI_USER 
GO
ALTER DATABASE [WebApiSecurityDb] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [WebApiSecurityDb] SET DB_CHAINING OFF 
GO
ALTER DATABASE [WebApiSecurityDb] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO
USE [WebApiSecurityDb]
GO
/****** Object:  Table [dbo].[UserRegistration]    Script Date: 23-11-2015 17:46:15 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[APIUser](
	[APIUserId] [int] IDENTITY(1,1) NOT NULL,
	[APIUserKey] [uniqueidentifier] NULL,
	[APIUserName] [nvarchar](50) NULL,
	[APIUserRole] [nvarchar](50) NULL,
 CONSTRAINT [PK_APIUser] PRIMARY KEY CLUSTERED 
(
	[APIUserId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]


