//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TransactionServiceClient.TransactionServiceReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Employee", Namespace="http://schemas.datacontract.org/2004/07/TransactionServiceLibrary")]
    [System.SerializableAttribute()]
    public partial class Employee : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ENameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double ESalaryField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int EidField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EName {
            get {
                return this.ENameField;
            }
            set {
                if ((object.ReferenceEquals(this.ENameField, value) != true)) {
                    this.ENameField = value;
                    this.RaisePropertyChanged("EName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double ESalary {
            get {
                return this.ESalaryField;
            }
            set {
                if ((this.ESalaryField.Equals(value) != true)) {
                    this.ESalaryField = value;
                    this.RaisePropertyChanged("ESalary");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Eid {
            get {
                return this.EidField;
            }
            set {
                if ((this.EidField.Equals(value) != true)) {
                    this.EidField = value;
                    this.RaisePropertyChanged("Eid");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SalaryHistory", Namespace="http://schemas.datacontract.org/2004/07/TransactionServiceLibrary")]
    [System.SerializableAttribute()]
    public partial class SalaryHistory : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double ESalaryField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> EdDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int EidField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int SNoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime StDateField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double ESalary {
            get {
                return this.ESalaryField;
            }
            set {
                if ((this.ESalaryField.Equals(value) != true)) {
                    this.ESalaryField = value;
                    this.RaisePropertyChanged("ESalary");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> EdDate {
            get {
                return this.EdDateField;
            }
            set {
                if ((this.EdDateField.Equals(value) != true)) {
                    this.EdDateField = value;
                    this.RaisePropertyChanged("EdDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Eid {
            get {
                return this.EidField;
            }
            set {
                if ((this.EidField.Equals(value) != true)) {
                    this.EidField = value;
                    this.RaisePropertyChanged("Eid");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int SNo {
            get {
                return this.SNoField;
            }
            set {
                if ((this.SNoField.Equals(value) != true)) {
                    this.SNoField = value;
                    this.RaisePropertyChanged("SNo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime StDate {
            get {
                return this.StDateField;
            }
            set {
                if ((this.StDateField.Equals(value) != true)) {
                    this.StDateField = value;
                    this.RaisePropertyChanged("StDate");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="TransactionServiceReference.IEmployeeSalary")]
    public interface IEmployeeSalary {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEmployeeSalary/CreateEmployee", ReplyAction="http://tempuri.org/IEmployeeSalary/CreateEmployeeResponse")]
        [System.ServiceModel.TransactionFlowAttribute(System.ServiceModel.TransactionFlowOption.Mandatory)]
        int CreateEmployee(TransactionServiceClient.TransactionServiceReference.Employee E);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEmployeeSalary/CreateEmployee", ReplyAction="http://tempuri.org/IEmployeeSalary/CreateEmployeeResponse")]
        System.Threading.Tasks.Task<int> CreateEmployeeAsync(TransactionServiceClient.TransactionServiceReference.Employee E);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEmployeeSalary/CreateSalaryHistory", ReplyAction="http://tempuri.org/IEmployeeSalary/CreateSalaryHistoryResponse")]
        [System.ServiceModel.TransactionFlowAttribute(System.ServiceModel.TransactionFlowOption.Mandatory)]
        void CreateSalaryHistory(TransactionServiceClient.TransactionServiceReference.SalaryHistory SH);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEmployeeSalary/CreateSalaryHistory", ReplyAction="http://tempuri.org/IEmployeeSalary/CreateSalaryHistoryResponse")]
        System.Threading.Tasks.Task CreateSalaryHistoryAsync(TransactionServiceClient.TransactionServiceReference.SalaryHistory SH);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IEmployeeSalaryChannel : TransactionServiceClient.TransactionServiceReference.IEmployeeSalary, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class EmployeeSalaryClient : System.ServiceModel.ClientBase<TransactionServiceClient.TransactionServiceReference.IEmployeeSalary>, TransactionServiceClient.TransactionServiceReference.IEmployeeSalary {
        
        public EmployeeSalaryClient() {
        }
        
        public EmployeeSalaryClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public EmployeeSalaryClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public EmployeeSalaryClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public EmployeeSalaryClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public int CreateEmployee(TransactionServiceClient.TransactionServiceReference.Employee E) {
            return base.Channel.CreateEmployee(E);
        }
        
        public System.Threading.Tasks.Task<int> CreateEmployeeAsync(TransactionServiceClient.TransactionServiceReference.Employee E) {
            return base.Channel.CreateEmployeeAsync(E);
        }
        
        public void CreateSalaryHistory(TransactionServiceClient.TransactionServiceReference.SalaryHistory SH) {
            base.Channel.CreateSalaryHistory(SH);
        }
        
        public System.Threading.Tasks.Task CreateSalaryHistoryAsync(TransactionServiceClient.TransactionServiceReference.SalaryHistory SH) {
            return base.Channel.CreateSalaryHistoryAsync(SH);
        }
    }
}
