//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BasicStreamingClient.WcfStreamingServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WcfStreamingServiceReference.IStreamService")]
    public interface IStreamService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStreamService/GetLargeObject", ReplyAction="http://tempuri.org/IStreamService/GetLargeObjectResponse")]
        System.IO.Stream GetLargeObject();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStreamService/GetLargeObject", ReplyAction="http://tempuri.org/IStreamService/GetLargeObjectResponse")]
        System.Threading.Tasks.Task<System.IO.Stream> GetLargeObjectAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IStreamServiceChannel : BasicStreamingClient.WcfStreamingServiceReference.IStreamService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class StreamServiceClient : System.ServiceModel.ClientBase<BasicStreamingClient.WcfStreamingServiceReference.IStreamService>, BasicStreamingClient.WcfStreamingServiceReference.IStreamService {
        
        public StreamServiceClient() {
        }
        
        public StreamServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public StreamServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public StreamServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public StreamServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.IO.Stream GetLargeObject() {
            return base.Channel.GetLargeObject();
        }
        
        public System.Threading.Tasks.Task<System.IO.Stream> GetLargeObjectAsync() {
            return base.Channel.GetLargeObjectAsync();
        }
    }
}
