//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SecureWebApiEg.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class APIUser
    {
        public int APIUserId { get; set; }
        public Nullable<System.Guid> APIUserKey { get; set; }
        public string APIUserName { get; set; }
        public string APIUserRole { get; set; }
    }
}
